### PR TITLE
Resolve [Bug]/#24

### LINKED ISSUE #24: [Bug]: @everyone role does not work for whitelisting
### Version information

1.0.0 Alpha 8

### Version type

Full

### Expected Behavior

users with no role/`@everyone` are able to use np!register to whitelist themselves

### Actual Behavior

"Sorry, but I couldn't accept your request
It seems that you don't have the required subscription/member level or don't have your Twitch/Youtube account linked to your Discord account."

### Reproduction Steps

1. Be a normal `@everyone` user
2. Type np!register <username> 
3. response is:
"Sorry, but I couldn't accept your request
It seems that you don't have the required subscription/member level or don't have your Twitch/Youtube account linked to your Discord account."

### Java version

N/A, issue with bot

### Additional information

Whitelisting self works with any role other than the default `@everyone`. Made a new role with no special permissions/not admin and it works, but I'd prefer if anyone joining the server with the default role could whitelist themselves.

### PR DESCRIPTION
**Pull request by csm-kb**
Resolves #24 

Reopening this using the newly-renamed fork branch version!

---

@Awakened-Redstone @kaydenvg
When executing the whitelist register command in Discord, we take the member's guild's getPublicRole() (which isn't returned in the list from getRoles() because it is documented as implicit):

The @everyone role; synonymous with the guild's ID.

and add it explicitly to the roles we're checking on the member.

This allows users to configure the mod using their guild's @everyone role, and have it behave as expected.

### CODE REVIEW

File: src/main/java/com/awakenedredstone/autowhitelist/discord/BotHelper.java [hunk 1]
```diff
@@ -74,6 +79,12 @@ public static void sendTempSimpleMessage(MessageChannel channel, Text message, i
         messageAction.queue(m -> m.delete().queueAfter(seconds, TimeUnit.SECONDS));
     }
 
+    public static List<Role> getRolesForMember(Member member) {
+        List<Role> roles = member.getRoles();
```
Comment (Awakened-Redstone) [inline src/main/java/com/awakenedredstone/autowhitelist/discord/BotHelper.java:83]:
```suggestion
        List<Role> roles = new ArrayList(member.getRoles());
```
MemberImpl#getRoles returns `Collections.unmodifiableList(roleList)`
I was trying to avoid doing this to not risk mem leak but I think I'm being worried for nothing

Other than that, everything looks great

**Review by Awakened-Redstone — CHANGES_REQUESTED** [review]

File: src/main/java/com/awakenedredstone/autowhitelist/discord/BotHelper.java (hunk 1 above)
Comment (csm-kb) [reply src/main/java/com/awakenedredstone/autowhitelist/discord/BotHelper.java]: That's what I would bet, given https://stackoverflow.com/questions/53767722/converting-immutable-to-mutable-list-java-is-there-any-alternative and the dig into it shows a literal transmutation of the underlying iterable into a new memory object

**Review by Awakened-Redstone — APPROVED** [review]

File: src/main/java/com/awakenedredstone/autowhitelist/discord/BotHelper.java (hunk 1 above)
Comment (csm-kb) [reply src/main/java/com/awakenedredstone/autowhitelist/discord/BotHelper.java]: (in my rebasing I somehow lost the arraylist change, so added that back)

**Comment by Awakened-Redstone** [comment]
I'll run some tests later to check for any odd behavior and errors, I'm quite busy recently but I should be able to run the tests this weekend.

File: src/main/java/com/awakenedredstone/autowhitelist/discord/BotHelper.java (hunk 1 above)
Comment (Awakened-Redstone) [reply src/main/java/com/awakenedredstone/autowhitelist/discord/BotHelper.java]: > That's what I would bet, given https://stackoverflow.com/questions/53767722/converting-immutable-to-mutable-list-java-is-there-any-alternative and the dig into it shows a literal transmutation of the underlying iterable into a new memory object

Yeah, that is why I had a worry on that, but the GC should take care of that, else Java would blow up

**Comment by Awakened-Redstone** [comment]
Mostly it looks good, there are a few things that need fixing but I can do that on a new commit
I'll also do some code cleaning
